# After every change to this file do:
# docker deploy fmp2copernic --compose-file docker-compose.yml

version: '3'

services:
  server:
    image: epflsti/fmp2copernic-server
    # See ./Dockerfile for what "build" consists of:
    build: .
    ports:
      - "3000:3000"
